### PR TITLE
Suppress autocmds errors

### PR DESCRIPTION
**Pull request by tani**
We just run `:` by `autocmd Users tsdetect#detect :` . It suppresses undefined autocmds errors.
P.S. This pull request participates hacktoberfest. Please add the label. Thanks.

### CODE REVIEW

**Comment by LumaKernel** [comment]
Oh, thanks! That's what I just thought!

How about adding all events written in readme?

**Comment by tani** [comment]
Yes. I have added all events.

**Comment by LumaKernel** [comment]
Can you put back what you moved in https://github.com/LumaKernel/vim-tsdetect/pull/10 please?

I want to init as fast as possible to prevent missing events after launching vim ( if installed through CocInstall )

**Comment by tani** [comment]
Noted and I have done it just now.

**Pull request merged**
